version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - db_data:/var/lib/mysql
    platform: linux/amd64

volumes:
  db_data:
